### ISSUE TITLE
my neoforge server 1.21.1  21.1.64 cant open

### ISSUE THREAD

**Issue by sharkbear552004** [SashaKYotoz/wrathy_armament#1]
my neoforge server 1.21.1  21.1.64 cant open
[debug.log](https://github.com/user-attachments/files/17278846/debug.log)

**Comment by SashaKYotoz** [comment]
Thanks for sending log, as i see problem appeared on RenderLayerEvent set up.

Fix will be released soon!

**Comment by SashaKYotoz** [comment]
v1.0.1.2 of WA released, and as i tested issue has been fixed
